# Train.py
# PURPOSE: Train 3 ML models and export as C header files for ESP32-S3
#
# PREREQUISITES:
#   pip install numpy pandas scikit-learn tensorflow micromlgen
#
# INPUT:  fan_dataset.csv (generated by collect_data.py)
# OUTPUT: dt_model.h  (Decision Tree)
#         rf_model.h  (Random Forest)
#         nn_model.h  (Neural Network weights + scaler params)
#
# HOW TO RUN:
#   cd C:\fanalyzer\training
#   python Train.py
#
# MODELS:
#   1. Decision Tree  (max_depth=6)      ~96-97% accuracy
#   2. Random Forest  (15 trees, depth=6) ~97-98% accuracy
#   3. Neural Network (3->16->8->4)       ~98-99% accuracy

import sys
sys.stdout.reconfigure(encoding='utf-8')

import numpy as np
import pandas as pd
import warnings
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow import keras
warnings.filterwarnings('ignore')

# ─── CONFIG ──────────────────────────────────────────────────
N_SAMPLES   = 128
SAMPLE_RATE = 500
N_CLASSES   = 4
CLASS_NAMES = ['normal', 'blocked', 'unbalanced', 'off']
# ─────────────────────────────────────────────────────────────


# ════════════════════════════════════════════════════════════
#  FEATURE EXTRACTION — must match ESP32 EXACTLY
#  ESP32 applies: Hamming window -> FFT -> 3 features
#  So Python must also apply: Hamming window -> FFT -> 3 features
# ════════════════════════════════════════════════════════════

def extract_fft_features(raw_window, sample_rate=SAMPLE_RATE):
    n = len(raw_window)

    # Apply Hamming window — MUST match ESP32's FFT.windowing(Hamming)
    # This was a bug in the original code (missing Hamming in training)
    hamming = np.hamming(n)
    windowed = raw_window * hamming

    # FFT
    fft_vals   = np.fft.rfft(windowed)
    magnitudes = np.abs(fft_vals)[:n // 2]

    # Extract 3 features (skip DC bin 0)
    dominant_bin  = np.argmax(magnitudes[1:]) + 1
    dominant_freq = dominant_bin * (sample_rate / n)
    max_amplitude = np.max(magnitudes[1:])
    mean_energy   = np.mean(magnitudes[1:])

    return [dominant_freq, max_amplitude, mean_energy]


# ════════════════════════════════════════════════════════════
#  LOAD DATA
# ════════════════════════════════════════════════════════════

def load_and_extract(csv_path="fan_dataset.csv"):
    print(f"  Loading: {csv_path}")
    df = pd.read_csv(csv_path)

    print(f"\n  Class distribution:")
    for label, count in df['label'].value_counts().sort_index().items():
        print(f"    Class {int(label)} ({CLASS_NAMES[int(label)]}): {count} windows")

    X, y = [], []
    for _, row in df.iterrows():
        raw      = row[[f's{i}' for i in range(N_SAMPLES)]].values.astype(float)
        features = extract_fft_features(raw)
        X.append(features)
        y.append(int(row['label']))

    X = np.array(X)
    y = np.array(y)
    print(f"\n  Feature matrix shape: {X.shape}")
    print(f"  Features: [dominant_freq, max_amplitude, mean_energy]")
    return X, y


# ════════════════════════════════════════════════════════════
#  MODEL 1: DECISION TREE
# ════════════════════════════════════════════════════════════

def generate_dt_manual(clf):
    """Fallback: generate dt_model.h manually if micromlgen unavailable."""
    from sklearn.tree import _tree
    tree = clf.tree_
    lines = []
    lines.append("// Auto-generated Decision Tree")
    lines.append("// Classes: 0=normal  1=blocked  2=unbalanced  3=off")
    lines.append("")
    lines.append("int dt_predict(float dom_freq, float max_amp, float mean_energy) {")
    lines.append("  float f[3] = {dom_freq, max_amp, mean_energy};")

    def recurse(node, depth):
        indent = "  " * (depth + 1)
        if tree.feature[node] != _tree.TREE_UNDEFINED:
            lines.append(f"{indent}if (f[{tree.feature[node]}] <= {tree.threshold[node]:.6f}f) {{")
            recurse(tree.children_left[node], depth + 1)
            lines.append(f"{indent}}} else {{")
            recurse(tree.children_right[node], depth + 1)
            lines.append(f"{indent}}}")
        else:
            pred = int(np.argmax(tree.value[node]))
            lines.append(f"{indent}return {pred};  // {CLASS_NAMES[pred]}")

    recurse(0, 0)
    lines.append("}")

    with open("dt_model.h", 'w') as f:
        f.write('\n'.join(lines))
    print("  Saved: dt_model.h (manual export)")


def train_decision_tree(X_train, X_test, y_train, y_test):
    print("\n" + "=" * 50)
    print("  MODEL 1: Decision Tree (max_depth=6)")
    print("=" * 50)

    clf = DecisionTreeClassifier(max_depth=6, random_state=42)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    acc = (y_pred == y_test).mean()

    print(f"\n  Accuracy: {acc * 100:.1f}%\n")
    print(classification_report(y_test, y_pred, target_names=CLASS_NAMES))
    print("  Confusion Matrix:")
    print(pd.DataFrame(
        confusion_matrix(y_test, y_pred),
        index=CLASS_NAMES, columns=CLASS_NAMES
    ), "\n")

    try:
        from micromlgen import port
        c_code = port(clf, classmap={0: 'normal', 1: 'blocked', 2: 'unbalanced', 3: 'off'})
        with open("dt_model.h", 'w') as f:
            f.write(c_code)
        print("  Saved: dt_model.h (micromlgen)")
    except ImportError:
        print("  micromlgen not found, using manual export...")
        generate_dt_manual(clf)
    return acc


# ════════════════════════════════════════════════════════════
#  MODEL 2: RANDOM FOREST
# ════════════════════════════════════════════════════════════

def train_random_forest(X_train, X_test, y_train, y_test):
    print("\n" + "=" * 50)
    print("  MODEL 2: Random Forest (15 trees, max_depth=6)")
    print("=" * 50)

    clf = RandomForestClassifier(n_estimators=15, max_depth=6, random_state=42)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    acc = (y_pred == y_test).mean()

    print(f"\n  Accuracy: {acc * 100:.1f}%\n")
    print(classification_report(y_test, y_pred, target_names=CLASS_NAMES))
    print("  Confusion Matrix:")
    print(pd.DataFrame(
        confusion_matrix(y_test, y_pred),
        index=CLASS_NAMES, columns=CLASS_NAMES
    ), "\n")

    try:
        from micromlgen import port
        c_code = port(clf, classmap={0: 'normal', 1: 'blocked', 2: 'unbalanced', 3: 'off'})
        with open("rf_model.h", 'w') as f:
            f.write(c_code)
        print("  Saved: rf_model.h (micromlgen)")
    except ImportError:
        print("  ERROR: micromlgen required for RF export.")
        print("  Install: pip install micromlgen==1.1.99")
    return acc


# ════════════════════════════════════════════════════════════
#  MODEL 3: NEURAL NETWORK
# ════════════════════════════════════════════════════════════

def export_nn_weights(model, scaler):
    """Export NN weights + StandardScaler params as C header file."""
    lines = []
    lines.append("// Auto-generated Neural Network weights for ESP32")
    lines.append("// Architecture: 3 -> 16 -> 8 -> 4")
    lines.append("// Classes: 0=normal  1=blocked  2=unbalanced  3=off")
    lines.append("// Hamming window MUST be applied before FFT")
    lines.append("")

    # StandardScaler parameters
    mean_str = ", ".join([f"{v:.8f}f" for v in scaler.mean_])
    std_str  = ", ".join([f"{v:.8f}f" for v in scaler.scale_])
    lines.append("// StandardScaler parameters (mean and std per feature)")
    lines.append(f"const float SCALER_MEAN[3] = {{{mean_str}}};")
    lines.append(f"const float SCALER_STD[3]  = {{{std_str}}};")
    lines.append("")

    # Extract weights from each dense layer
    dense_layers = [l for l in model.layers if len(l.get_weights()) == 2]
    layer_sizes = [3]  # Input size

    for idx, layer in enumerate(dense_layers):
        W, b = layer.get_weights()
        in_size, out_size = W.shape
        layer_sizes.append(out_size)

        lines.append(f"// Layer {idx+1}: {in_size} -> {out_size}")
        lines.append(f"const float W{idx+1}[{in_size}][{out_size}] = {{")
        for row in W:
            lines.append("  {" + ", ".join([f"{v:.8f}f" for v in row]) + "},")
        lines.append("};")
        b_str = ", ".join([f"{v:.8f}f" for v in b])
        lines.append(f"const float b{idx+1}[{out_size}] = {{{b_str}}};")
        lines.append("")

    # Layer size defines
    for i, size in enumerate(layer_sizes):
        lines.append(f"#define NN_LAYER_{i}_SIZE {size}")
    lines.append("")
    lines.append("inline float relu(float x) { return x > 0 ? x : 0; }")

    with open("nn_model.h", 'w') as f:
        f.write('\n'.join(lines))
    print("  Saved: nn_model.h")


def train_neural_network(X_train, X_test, y_train, y_test):
    print("\n" + "=" * 50)
    print("  MODEL 3: Neural Network (3->16->8->4)")
    print("=" * 50)

    # Normalize features
    scaler    = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s  = scaler.transform(X_test)

    # One-hot encode labels
    y_train_oh = keras.utils.to_categorical(y_train, N_CLASSES)
    y_test_oh  = keras.utils.to_categorical(y_test, N_CLASSES)

    # Build model
    model = keras.Sequential([
        keras.layers.Input(shape=(3,)),
        keras.layers.Dense(16, activation='relu'),
        keras.layers.Dense(8, activation='relu'),
        keras.layers.Dense(N_CLASSES, activation='softmax'),
    ])
    model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    print("  Training (150 epochs)...")
    model.fit(
        X_train_s, y_train_oh,
        epochs=150,
        batch_size=16,
        validation_split=0.15,
        verbose=0
    )

    # Evaluate
    _, acc = model.evaluate(X_test_s, y_test_oh, verbose=0)
    y_pred = np.argmax(model.predict(X_test_s, verbose=0), axis=1)

    print(f"\n  Accuracy: {acc * 100:.1f}%\n")
    print(classification_report(y_test, y_pred, target_names=CLASS_NAMES))
    print("  Confusion Matrix:")
    print(pd.DataFrame(
        confusion_matrix(y_test, y_pred),
        index=CLASS_NAMES, columns=CLASS_NAMES
    ), "\n")

    # Export weights
    export_nn_weights(model, scaler)
    return acc


# ════════════════════════════════════════════════════════════
#  MAIN
# ════════════════════════════════════════════════════════════

def main():
    print("=" * 50)
    print("  Fanalyzer - Model Training Pipeline")
    print("  Classes: normal / blocked / unbalanced / off")
    print("  Hamming window: ENABLED (matches ESP32)")
    print("=" * 50)

    X, y = load_and_extract()

    # Check all classes present
    missing = [CLASS_NAMES[i] for i in range(N_CLASSES) if i not in np.unique(y)]
    if missing:
        print(f"\n  ERROR: Missing classes: {missing}")
        print("  Run collect_data.py to collect all 4 classes first.")
        return

    # Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"\n  Train: {len(X_train)} samples  |  Test: {len(X_test)} samples")

    # Train all 3 models
    acc_dt = train_decision_tree(X_train, X_test, y_train, y_test)
    acc_rf = train_random_forest(X_train, X_test, y_train, y_test)
    acc_nn = train_neural_network(X_train, X_test, y_train, y_test)

    # Summary
    print("=" * 50)
    print("  FINAL RESULTS")
    print("=" * 50)
    results = [
        ("Decision Tree",  acc_dt),
        ("Random Forest",  acc_rf),
        ("Neural Network", acc_nn),
    ]
    for name, acc in results:
        bar = "#" * int(acc * 20)
        print(f"  {name:<16} {acc*100:5.1f}%  [{bar:<20}]")

    best = max(results, key=lambda x: x[1])
    print(f"\n  Best model: {best[0]} ({best[1]*100:.1f}%)")
    print("\n  Generated files:")
    print("    dt_model.h  ->  for fanalyzer_decision_tree/")
    print("    rf_model.h  ->  for fanalyzer_random_forest/")
    print("    nn_model.h  ->  for fanalyzer_neural_network/")
    print("\n  Copy nn_model.h into the firmware folder before uploading!")


if __name__ == "__main__":
    main()
